name: github action hol 1

on:
  push:
    branches:
      - gh-act-hol1
    
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
      - name: Install required binaries
        run: |
             cd function
             python -m pip install --upgrade pip
             pip install -r requirements.txt -t .
    
