name: github action hol 1

on:
  push:
    branches:
      - main
    
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
      - name: Install required binaries
        run: |
             cd function
             python -m pip install --upgrade pip
             pip install -r requirements.txt -t .
